### ISSUE TITLE
Cannot find module 'del'

### ISSUE THREAD

**Issue by Rudloff** [tunnela/cordova-hook-ignore-files#1]
I get this error  when running `cordova build`:
```
Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/pierre/www/openvegemap-cordova/node_modules/cordova-hook-ignore-files/ignore-files.js:4:9)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
```

**Comment by tunnela** [comment]
@Rudloff Thank you for reporting this! I will push a fix today at some point. Before that you can just install the depencencies by running `npm i --save del glob q xml2js`
